name: infra

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "infra/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_postgres_connection_string: ${{ secrets.POSTGRES_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        working-directory: infra
        run: terraform init
      - name: Terraform validate
        working-directory: infra
        run: terraform validate
      - name: Terraform plan
        working-directory: infra
        run: terraform plan -out=tfplan
